name: explorator
description: A routing system which fits perfectly between catalyst_builder and the flutter router.
version: 1.2.0
repository: https://github.com/mintware-de/explorator

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  catalyst_builder: '>=3.2.2 <5.0.0'
  flutter:
    sdk: flutter
  mockito: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  test: ^1.22.1

