name: explorator
description: A routing system which fits perfectly between catalyst_builder and the flutter router.
version: 2.0.0-rc.1
repository: https://github.com/mintware-de/explorator

environment:
  sdk: ^3.6.0
  flutter: '>=3.0.0'

dependencies:
  catalyst_builder_contracts: ^2.0.0-rc.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.2.0
  test: ^1.22.1
  catalyst_builder: ^5.0.0-rc.1

  mockito: ^5.0.0
