name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: dart analyze lib

      - name: Generate the mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test